### PR TITLE
Update windows.md

### PR DESCRIPTION
**Pull request by Pitoniso**

### CODE REVIEW

**Comment by jtl999** [comment]
Forked this pull requests and made some modifications in #21

**Comment by Pitoniso** [comment]
If you prefer it this way, post it. In my opinion it would be good to add the previous build number which were good.

What happens with the graphic card page I also edited?


________________________________
De: JTL <notifications@github.com>
Enviat el: dissabte, 9 de maig de 2020 23:24
Per a: ledstrain/wiki.ledstrain.org <wiki.ledstrain.org@noreply.github.com>
A/c: Pitoniso <xatarra2@outlook.es>; Author <author@noreply.github.com>
Tema: Re: [ledstrain/wiki.ledstrain.org] Update windows.md (#20)

Forked this pull requests and made some modifications in #21<https://github.com/ledstrain/wiki.ledstrain.org/pull/21>

**Comment by jtl999** [comment]
> If you prefer it this way, post it. In my opinion it would be good to add the previous build number which were good.

Fixed that

> What happens with the graphic card page I also edited?

It's still exists. It's informally "on hold" pending Slacor's input.

**Comment by jtl999** [comment]
Superseded by #21

**Pull request closed without merging**
